# Generated from docs/openapi.yaml by :sdks:shared. Do not edit.
#
# `./gradlew :sdks:shared:generateSdkSources` regenerates this module;
# `./gradlew :sdks:shared:verifySdkSources` fails the build when it is stale,
# which is why hand-editing it is not merely discouraged but pointless.

from __future__ import annotations

from typing import Dict, Final, Tuple, TypedDict


class OperationDescriptor(TypedDict):
    """One published operation, addressed by the operation id M21.7 made unique."""

    id: str
    method: str
    path: str
    tag: str
    summary: str
    success_status: str
    query_parameters: Tuple[str, ...]
    required_headers: Tuple[str, ...]
    has_request_body: bool


OPERATIONS: Final[Dict[str, OperationDescriptor]] = {
    "getPaymentAnalytics": {
        "id": "getPaymentAnalytics",
        "method": "GET",
        "path": "/v1/analytics/payments",
        "tag": "Analytics",
        "summary": "Summarize payment activity",
        "success_status": "200",
        "query_parameters": ("from", "to", ),
        "required_headers": (),
        "has_request_body": False,
    },
    "getBalance": {
        "id": "getBalance",
        "method": "GET",
        "path": "/v1/balance",
        "tag": "Balance",
        "summary": "Retrieve your balance",
        "success_status": "200",
        "query_parameters": (),
        "required_headers": (),
        "has_request_body": False,
    },
    "listBalanceTransactions": {
        "id": "listBalanceTransactions",
        "method": "GET",
        "path": "/v1/balance_transactions",
        "tag": "Balance transactions",
        "summary": "List balance transactions",
        "success_status": "200",
        "query_parameters": ("limit", "starting_after", "created_after", "created_before", ),
        "required_headers": (),
        "has_request_body": False,
    },
    "listEvents": {
        "id": "listEvents",
        "method": "GET",
        "path": "/v1/events",
        "tag": "Events",
        "summary": "List events",
        "success_status": "200",
        "query_parameters": ("limit", "starting_after", "type", "created_after", "created_before", ),
        "required_headers": (),
        "has_request_body": False,
    },
    "getEvent": {
        "id": "getEvent",
        "method": "GET",
        "path": "/v1/events/{id}",
        "tag": "Events",
        "summary": "Retrieve an event",
        "success_status": "200",
        "query_parameters": (),
        "required_headers": (),
        "has_request_body": False,
    },
    "listPayments": {
        "id": "listPayments",
        "method": "GET",
        "path": "/v1/payments",
        "tag": "Payments",
        "summary": "List payments",
        "success_status": "200",
        "query_parameters": ("limit", "starting_after", "status", "currency", "amount_min", "amount_max", "created_after", "created_before", "expand", "metadata", ),
        "required_headers": (),
        "has_request_body": False,
    },
    "createPayment": {
        "id": "createPayment",
        "method": "POST",
        "path": "/v1/payments",
        "tag": "Payments",
        "summary": "Create a payment",
        "success_status": "201",
        "query_parameters": (),
        "required_headers": ("Idempotency-Key", ),
        "has_request_body": True,
    },
    "getPayment": {
        "id": "getPayment",
        "method": "GET",
        "path": "/v1/payments/{id}",
        "tag": "Payments",
        "summary": "Retrieve a payment",
        "success_status": "200",
        "query_parameters": ("expand", ),
        "required_headers": (),
        "has_request_body": False,
    },
    "authorizePayment": {
        "id": "authorizePayment",
        "method": "POST",
        "path": "/v1/payments/{id}/authorize",
        "tag": "Payments",
        "summary": "Authorize a payment",
        "success_status": "200",
        "query_parameters": (),
        "required_headers": ("Idempotency-Key", ),
        "has_request_body": False,
    },
    "capturePayment": {
        "id": "capturePayment",
        "method": "POST",
        "path": "/v1/payments/{id}/capture",
        "tag": "Payments",
        "summary": "Capture an authorized payment",
        "success_status": "200",
        "query_parameters": (),
        "required_headers": ("Idempotency-Key", ),
        "has_request_body": False,
    },
    "refundPayment": {
        "id": "refundPayment",
        "method": "POST",
        "path": "/v1/payments/{id}/refund",
        "tag": "Payments",
        "summary": "Refund a captured payment",
        "success_status": "200",
        "query_parameters": (),
        "required_headers": ("Idempotency-Key", ),
        "has_request_body": True,
    },
    "voidPayment": {
        "id": "voidPayment",
        "method": "POST",
        "path": "/v1/payments/{id}/void",
        "tag": "Payments",
        "summary": "Void a payment",
        "success_status": "200",
        "query_parameters": (),
        "required_headers": ("Idempotency-Key", ),
        "has_request_body": False,
    },
    "listRefunds": {
        "id": "listRefunds",
        "method": "GET",
        "path": "/v1/refunds",
        "tag": "Refunds",
        "summary": "List refunds",
        "success_status": "200",
        "query_parameters": ("limit", "starting_after", "payment", "status", "created_after", "created_before", "metadata", ),
        "required_headers": (),
        "has_request_body": False,
    },
    "getRefund": {
        "id": "getRefund",
        "method": "GET",
        "path": "/v1/refunds/{id}",
        "tag": "Refunds",
        "summary": "Retrieve a refund",
        "success_status": "200",
        "query_parameters": (),
        "required_headers": (),
        "has_request_body": False,
    },
    "listRequestLogs": {
        "id": "listRequestLogs",
        "method": "GET",
        "path": "/v1/request_logs",
        "tag": "Request logs",
        "summary": "List API request logs",
        "success_status": "200",
        "query_parameters": ("limit", "starting_after", "created_after", "created_before", "status_code", "method", ),
        "required_headers": (),
        "has_request_body": False,
    },
    "listTestCards": {
        "id": "listTestCards",
        "method": "GET",
        "path": "/v1/test/cards",
        "tag": "Test cards",
        "summary": "List the test cards",
        "success_status": "200",
        "query_parameters": (),
        "required_headers": (),
        "has_request_body": False,
    },
    "listSandboxDecisions": {
        "id": "listSandboxDecisions",
        "method": "GET",
        "path": "/v1/test/decisions",
        "tag": "Decisions",
        "summary": "List sandbox decisions",
        "success_status": "200",
        "query_parameters": ("page", "size", "sort", ),
        "required_headers": (),
        "has_request_body": False,
    },
    "listSandboxDecisionsForPayment": {
        "id": "listSandboxDecisionsForPayment",
        "method": "GET",
        "path": "/v1/test/decisions/payments/{paymentId}",
        "tag": "Decisions",
        "summary": "List the decisions for one payment",
        "success_status": "200",
        "query_parameters": (),
        "required_headers": (),
        "has_request_body": False,
    },
    "createSimulationOverride": {
        "id": "createSimulationOverride",
        "method": "POST",
        "path": "/v1/test/simulations",
        "tag": "Simulations",
        "summary": "Force a sandbox behaviour",
        "success_status": "201",
        "query_parameters": (),
        "required_headers": (),
        "has_request_body": True,
    },
    "revokeActiveSimulationOverride": {
        "id": "revokeActiveSimulationOverride",
        "method": "DELETE",
        "path": "/v1/test/simulations/active",
        "tag": "Simulations",
        "summary": "Revoke the active override",
        "success_status": "204",
        "query_parameters": (),
        "required_headers": (),
        "has_request_body": False,
    },
    "getActiveSimulationOverride": {
        "id": "getActiveSimulationOverride",
        "method": "GET",
        "path": "/v1/test/simulations/active",
        "tag": "Simulations",
        "summary": "Retrieve the active override",
        "success_status": "200",
        "query_parameters": (),
        "required_headers": (),
        "has_request_body": False,
    },
    "getUsage": {
        "id": "getUsage",
        "method": "GET",
        "path": "/v1/usage",
        "tag": "Usage",
        "summary": "Summarize API usage",
        "success_status": "200",
        "query_parameters": ("from", "to", ),
        "required_headers": (),
        "has_request_body": False,
    },
    "listWebhookDeliveries": {
        "id": "listWebhookDeliveries",
        "method": "GET",
        "path": "/v1/webhook_deliveries",
        "tag": "Webhook deliveries",
        "summary": "List webhook deliveries",
        "success_status": "200",
        "query_parameters": ("page", "size", "sort", ),
        "required_headers": (),
        "has_request_body": False,
    },
    "getWebhookDelivery": {
        "id": "getWebhookDelivery",
        "method": "GET",
        "path": "/v1/webhook_deliveries/{id}",
        "tag": "Webhook deliveries",
        "summary": "Retrieve a webhook delivery",
        "success_status": "200",
        "query_parameters": (),
        "required_headers": (),
        "has_request_body": False,
    },
    "replayWebhookDelivery": {
        "id": "replayWebhookDelivery",
        "method": "POST",
        "path": "/v1/webhook_deliveries/{id}/replay",
        "tag": "Webhook deliveries",
        "summary": "Replay a webhook delivery",
        "success_status": "201",
        "query_parameters": (),
        "required_headers": (),
        "has_request_body": False,
    },
    "listWebhookEndpoints": {
        "id": "listWebhookEndpoints",
        "method": "GET",
        "path": "/v1/webhook_endpoints",
        "tag": "Webhook endpoints",
        "summary": "List your webhook endpoints",
        "success_status": "200",
        "query_parameters": (),
        "required_headers": (),
        "has_request_body": False,
    },
    "createWebhookEndpoint": {
        "id": "createWebhookEndpoint",
        "method": "POST",
        "path": "/v1/webhook_endpoints",
        "tag": "Webhook endpoints",
        "summary": "Register a webhook endpoint",
        "success_status": "201",
        "query_parameters": (),
        "required_headers": (),
        "has_request_body": True,
    },
    "deleteWebhookEndpoint": {
        "id": "deleteWebhookEndpoint",
        "method": "DELETE",
        "path": "/v1/webhook_endpoints/{id}",
        "tag": "Webhook endpoints",
        "summary": "Delete a webhook endpoint",
        "success_status": "204",
        "query_parameters": (),
        "required_headers": (),
        "has_request_body": False,
    },
    "getWebhookEndpoint": {
        "id": "getWebhookEndpoint",
        "method": "GET",
        "path": "/v1/webhook_endpoints/{id}",
        "tag": "Webhook endpoints",
        "summary": "Retrieve a webhook endpoint",
        "success_status": "200",
        "query_parameters": (),
        "required_headers": (),
        "has_request_body": False,
    },
    "updateWebhookEndpoint": {
        "id": "updateWebhookEndpoint",
        "method": "PATCH",
        "path": "/v1/webhook_endpoints/{id}",
        "tag": "Webhook endpoints",
        "summary": "Update a webhook endpoint",
        "success_status": "200",
        "query_parameters": (),
        "required_headers": (),
        "has_request_body": True,
    },
    "rotateWebhookEndpointSecret": {
        "id": "rotateWebhookEndpointSecret",
        "method": "POST",
        "path": "/v1/webhook_endpoints/{id}/rotate_secret",
        "tag": "Webhook endpoints",
        "summary": "Rotate an endpoint's signing secret",
        "success_status": "200",
        "query_parameters": (),
        "required_headers": (),
        "has_request_body": False,
    },
}
